const $ = (selector) => document.querySelector(selector);
const defaultConfig = {strategy:{version:"strategy-v1",timeframe_weights:{"15m":0.15,"1h":0.35,"4h":0.3,"1d":0.2},entry_threshold:0.7,exit_threshold:0.7,minimum_confidence:0.6,minimum_confirming_groups:2,indicator_parameters:{rsi_period:14,ema_fast:20,ema_slow:50},pattern_parameters:{min_confidence:0.6}},risk:{max_position_fraction:0.25,max_daily_loss_fraction:0.03,max_drawdown_fraction:0.2},costs:{fee_rate:0.001,spread_bps:5,slippage_bps:5}};
$("textarea[name=configuration]").value = JSON.stringify(defaultConfig, null, 2);
function showPanel(name){document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id===name));document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.panel===name));if(name==="data") loadDatasets();}
document.querySelectorAll("[data-panel]").forEach(el=>el.addEventListener("click",()=>showPanel(el.dataset.panel)));
function notice(message=""){ $("#notice").textContent=message; }
async function request(url, options={}){const response=await fetch(url,options);const body=await response.json().catch(()=>({}));if(!response.ok) throw new Error(body?.error?.message||`HTTP ${response.status}`);return body;}
function key(prefix){return `${prefix}-${crypto.randomUUID()}`;}
function renderResult(target, value){$(target).innerHTML=`<pre>${escapeHtml(JSON.stringify(value,null,2))}</pre>`;}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
async function refreshHealth(){try{const health=await request("/health/ready");$("#health").className="pill ok";$("#health").textContent="API bereit";$("#apiState").textContent=health.status;$("#apiDetail").textContent=Object.entries(health.dependencies||{}).map(([k,v])=>`${k}: ${v}`).join(" · ");}catch(error){$("#health").className="pill bad";$("#health").textContent="API nicht bereit";$("#apiState").textContent="offline";$("#apiDetail").textContent=error.message;}}
function formPayload(form){return Object.fromEntries(new FormData(form).entries());}
$("#backtestForm").addEventListener("submit",async event=>{event.preventDefault();try{const body=await request("/api/v1/backtests",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key("backtest")},body:JSON.stringify(formPayload(event.target))});renderResult("#backtestResult",body);notice("Backtest wurde eingereiht.");}catch(error){notice(error.message);}});
function renderPaper(body){const controls=["start","pause","resume","stop"].map(action=>`<button class="secondary paper-action" data-url="${body.resource_url}/${action}" data-action="${action}">${action}</button>`).join(" ");$("#paperResult").innerHTML=`<pre>${escapeHtml(JSON.stringify(body,null,2))}</pre><div>${controls}</div>`;document.querySelectorAll(".paper-action").forEach(button=>button.addEventListener("click",async()=>{try{const updated=await request(button.dataset.url,{method:"POST",headers:{"Idempotency-Key":key(`paper-${button.dataset.action}`)}});renderPaper(updated);notice(`Paper-Session: ${updated.state}`);}catch(error){notice(error.message);}}));}
$("#paperForm").addEventListener("submit",async event=>{event.preventDefault();try{const body=await request("/api/v1/paper-sessions",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key("paper")},body:JSON.stringify(formPayload(event.target))});renderPaper(body);notice("Paper-Session wurde erstellt und kann jetzt gesteuert werden.");}catch(error){notice(error.message);}});
$("#strategyForm").addEventListener("submit",async event=>{event.preventDefault();try{const configuration=JSON.parse(event.target.configuration.value);const body=await request("/api/v1/strategies/validate",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key("validate")},body:JSON.stringify({configuration})});renderResult("#strategyResult",body);notice("Strategiekonfiguration ist gültig.");}catch(error){notice(error instanceof SyntaxError?"Ungültiges JSON":error.message);}});
async function loadDatasets(){try{const body=await request("/api/v1/datasets?limit=100");const rows=(body.datasets||[]).map(item=>`<tr><td>${escapeHtml(item.id||item.dataset_id||"—")}</td><td>${escapeHtml(item.symbol||"BTC/USDT")}</td><td>${escapeHtml(item.timeframe||item.time_frame||"—")}</td></tr>`).join("");$("#datasets").innerHTML=rows?`<table class="table"><thead><tr><th>Datensatz</th><th>Symbol</th><th>Zeitebene</th></tr></thead><tbody>${rows}</tbody></table>`:"Keine Datensätze gefunden.";}catch(error){$("#datasets").textContent=error.message;}}
$("#refreshDatasets").addEventListener("click",loadDatasets);refreshHealth();
