"""Create the complete immutable trading-agent persistence contract."""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_foundation"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create all domain, runtime, audit and idempotency tables and indexes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        "ix_audit_subject_time", "audit_events", ["subject_id", "occurred_at"], unique=False
    )
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_backtest_runs_state"), "backtest_runs", ["state"], unique=False)
    op.create_table(
        "configuration_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_hash"),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("operation", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("result_type", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation", "idempotency_key", name="uq_idempotency_operation_key"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("maximum_retries", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_class", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "idempotency_key", name="uq_job_kind_idempotency"),
    )
    op.create_index("ix_jobs_claim", "jobs", ["status", "available_at", "created_at"], unique=False)
    op.create_index(op.f("ix_jobs_lease_expires_at"), "jobs", ["lease_expires_at"], unique=False)
    op.create_table(
        "market_datasets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_dataset_source_id"),
    )
    op.create_index("ix_market_datasets_page", "market_datasets", ["id"], unique=False)
    op.create_table(
        "paper_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("last_scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_paper_sessions_state"), "paper_sessions", ["state"], unique=False)
    op.create_table(
        "schema_versions",
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "strategy_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("configuration_hash"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "backtest_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["backtest_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_backtest_events_run_time", "backtest_events", ["run_id", "event_time"], unique=False
    )
    op.create_table(
        "backtest_metrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["backtest_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "name", name="uq_backtest_metric"),
    )
    op.create_table(
        "candles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("timeframe", sa.String(length=4), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("close_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("high", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("low", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("close", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("volume", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["market_datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "dataset_id", "symbol", "timeframe", "open_time", name="uq_candles_identity"
        ),
    )
    op.create_index(
        "ix_candles_lookup",
        "candles",
        ["dataset_id", "symbol", "timeframe", "open_time"],
        unique=False,
    )
    op.create_table(
        "cash_ledger",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("entry_type", sa.String(length=24), nullable=False),
        sa.Column("asset", sa.String(length=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("reference_id", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "reference_id", "entry_type", "asset", name="uq_ledger_ref_type_asset"
        ),
    )
    op.create_index("ix_cash_ledger_page", "cash_ledger", ["session_id", "id"], unique=False)
    op.create_index(
        "ix_cash_ledger_session_time", "cash_ledger", ["session_id", "occurred_at"], unique=False
    )
    op.create_table(
        "data_gaps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("timeframe", sa.String(length=4), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["market_datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "timeframe", "start_time", name="uq_data_gap"),
    )
    op.create_index("ix_data_gaps_open", "data_gaps", ["dataset_id", "resolved_at"], unique=False)
    op.create_index("ix_data_gaps_page", "data_gaps", ["dataset_id", "id"], unique=False)
    op.create_table(
        "equity_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("equity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("cash", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("btc_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "observed_at", name="uq_equity_session_time"),
    )
    op.create_table(
        "positions",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("btc_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("average_entry_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "candle_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("candle_id", sa.String(length=36), nullable=False),
        sa.Column("before", sa.JSON(), nullable=False),
        sa.Column("after", sa.JSON(), nullable=False),
        sa.Column("revised_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candle_id"],
            ["candles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_candle_revisions_candle_time",
        "candle_revisions",
        ["candle_id", "revised_at"],
        unique=False,
    )
    op.create_table(
        "feature_values",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("candle_id", sa.String(length=36), nullable=False),
        sa.Column("feature_name", sa.String(length=128), nullable=False),
        sa.Column("version_hash", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candle_id"],
            ["candles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candle_id", "feature_name", "version_hash", name="uq_feature_cache"),
    )
    op.create_index("ix_feature_values_candle", "feature_values", ["candle_id"], unique=False)
    op.create_table(
        "signal_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_session_id", sa.String(length=36), nullable=True),
        sa.Column("backtest_run_id", sa.String(length=36), nullable=True),
        sa.Column("candle_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("score", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("explanation", sa.JSON(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["backtest_run_id"],
            ["backtest_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["candle_id"],
            ["candles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_session_id"],
            ["paper_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_session_id", "candle_id", name="uq_paper_candle_decision"),
    )
    op.create_index(
        "ix_signal_decisions_page", "signal_decisions", ["paper_session_id", "id"], unique=False
    )
    op.create_index(
        "ix_signal_decisions_session_time",
        "signal_decisions",
        ["paper_session_id", "decided_at"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("decision_id", sa.String(length=36), nullable=True),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["signal_decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_orders_session_id"), "orders", ["session_id"], unique=False)
    op.create_table(
        "fills",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fee", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fills_order_id"), "fills", ["order_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop all application tables in dependency-safe order."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fills_order_id"), table_name="fills")
    op.drop_table("fills")
    op.drop_index(op.f("ix_orders_session_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_signal_decisions_session_time", table_name="signal_decisions")
    op.drop_index("ix_signal_decisions_page", table_name="signal_decisions")
    op.drop_table("signal_decisions")
    op.drop_index("ix_feature_values_candle", table_name="feature_values")
    op.drop_table("feature_values")
    op.drop_index("ix_candle_revisions_candle_time", table_name="candle_revisions")
    op.drop_table("candle_revisions")
    op.drop_table("positions")
    op.drop_table("equity_snapshots")
    op.drop_index("ix_data_gaps_page", table_name="data_gaps")
    op.drop_index("ix_data_gaps_open", table_name="data_gaps")
    op.drop_table("data_gaps")
    op.drop_index("ix_cash_ledger_session_time", table_name="cash_ledger")
    op.drop_index("ix_cash_ledger_page", table_name="cash_ledger")
    op.drop_table("cash_ledger")
    op.drop_index("ix_candles_lookup", table_name="candles")
    op.drop_table("candles")
    op.drop_table("backtest_metrics")
    op.drop_index("ix_backtest_events_run_time", table_name="backtest_events")
    op.drop_table("backtest_events")
    op.drop_table("strategy_definitions")
    op.drop_table("schema_versions")
    op.drop_index(op.f("ix_paper_sessions_state"), table_name="paper_sessions")
    op.drop_table("paper_sessions")
    op.drop_index("ix_market_datasets_page", table_name="market_datasets")
    op.drop_table("market_datasets")
    op.drop_index(op.f("ix_jobs_lease_expires_at"), table_name="jobs")
    op.drop_index("ix_jobs_claim", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("idempotency_records")
    op.drop_table("configuration_snapshots")
    op.drop_index(op.f("ix_backtest_runs_state"), table_name="backtest_runs")
    op.drop_table("backtest_runs")
    op.drop_index("ix_audit_subject_time", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
